services:
  database:
    image: postgres
    restart: always
    ports:
      - ${DATASOURCE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - database_data:/var/lib/postgres

  test-database:
    image: postgres
    restart: always
    ports:
      - ${TEST_DATASOURCE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${TEST_DATASOURCE_PASSWORD}

volumes:
  database_data: