services:
  database:
    image: postgres
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data

  test-database:
    image: postgres
    restart: always
    ports:
      - ${TEST_DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD}

volumes:
  database_data: